const mongoose = require("mongoose") ;
const Schema = mongoose.Schema ;

const Classes = new Schema({
  "classDetails":[{
    "class_number":{
        type:Number,
        required:true,
        min:1,
        default:1
    },
    "Capacity":{
        type:Number,
        default:0,
        min:0,
        required:true
    },
    "slot1":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                enum:[9],
                default:9
            },
            "to":{
                type:Number,
                default:10,
                enum:[10]
            }
        }
    },
    "slot2":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:10,
                enum:[10]
            },
            "to":{
                type:Number,
                default:11,
                enum:[11]
            }
        }
    },
    "slot3":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:11,
                enum:[11]
            },
            "to":{
                type:Number,
                default:12,
                enum:[12]
            }
        }
    },
    "slot4":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:12,
                enum:[12]
            },
            "to":{
                type:Number,
                default:1,
                enum:[1]
            }
        }
    },
    "slot5":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:2,
                enum:[2]
            },
            "to":{
                type:Number,
                default:3,
                enum:[3]
            }
        }
    },
    "slot6":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:3,
                enum:[3]
            },
            "to":{
                type:Number,
                default:4,
                enum:[4]
            }
        }
    },
    "slot7":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:4,
                enum:[4]
            },
            "to":{
                type:Number,
                default:5,
                enum:[5]
            }
        }
    },
    "slot8":{
        "status":{
            type:Boolean,
            default:false,
            required:true
        },
        "time":{
            "from":{
                type:Number,
                default:5,
                enum:[5]
            },
            "to":{
                type:Number,
                default:6,
                enum:[6]
            }
        }
    }
  }]
}) ;

module.exports = mongoose.model("Class",Classes) ;